require("dotenv").config({ path: "./.env" });
const express = require("express");
const app = express();
const bodyParser = require("body-parser");
const cors = require("cors");
const test = require("./services/app-service");

// var corsOptions = {
//   origin: ["http://localhost:3001"],
//   optionsSuccessStatus: 200, // some legacy browsers (IE11, various SmartTVs) choke on 204
//   methods: ["GET", "POST", "DELETE", "UPDATE", "PUT", "PATCH"],
// };

//app.use(cors(corsOptions));

app.use(cors());

app.use((req, res, next) => {
  // res.header("Access-Control-Allow-Origin", "*");
  // res.header("Access-Control-Allow-Methods", "GET, POST, OPTIONS, PUT, DELETE");
  // res.header("Allow", "GET, POST, OPTIONS, PUT, DELETE");
  // console.log(req.header());
  //console.log(res.getHeader());
  //res.write("you posted:\n");
  //res.end(JSON.stringify(req.body, null, 2));
  next();
});

// parse application/json
app.use(bodyParser.json());

// parse application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: true }));

app.use("/api/v1", require("./Routes/general-route")); /* buscar el orden */
process.env.HOST_PORT = 8081;
app.set(process.env.HOST_PORT);
app.listen(process.env.HOST_PORT);

console.log("API is runnning at " + process.env.HOST_PORT);

const msgs = [
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
  "msg: ",
];

const running = async (msg) => {
  msg = {
    from: "593982368622@c.us",
    body: "Hola Génesis",
    notifyName: "Jefferson Mena",
  };

  for (item of msgs) {
    const result = await test.testSaturacion(msg);
    console.log(msg, result);
  }

  //   ((msg, index) => {
  //   const result = await test.testSaturacion(msg);

  //   console.log(msg, result);
  // });
};

setTimeout(async () => {
  running();
  // array.forEach((msg, index) => {
  //   console.log("running...");
  //   msg = {
  //     from: "593982368622@c.us",
  //     body: "Hola Génesis",
  //     notifyName: "Jefferson Mena",
  //   };
  //   await running(msg + " " + (index + 1).toString());
  //   console.log("ending...");
  // });
}, 3000);
